# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_dataset": "00_core.ipynb",
         "rmse": "00_core.ipynb",
         "convert_strings_to_categories": "00_core.ipynb",
         "fill_missing_values_with_median": "00_core.ipynb",
         "make_polynomial_data": "00_core.ipynb",
         "PolynomialRegressor": "00_core.ipynb",
         "display_large": "00_core.ipynb",
         "rf_feature_importance": "00_core.ipynb",
         "plot_feature_importance": "00_core.ipynb",
         "plot_dendogram": "00_core.ipynb",
         "draw_tree": "01_structured.ipynb",
         "get_sample": "01_structured.ipynb",
         "add_datepart": "01_structured.ipynb",
         "is_date": "01_structured.ipynb",
         "train_cats": "01_structured.ipynb",
         "apply_cats": "01_structured.ipynb",
         "fix_missing": "01_structured.ipynb",
         "numericalize": "01_structured.ipynb",
         "scale_vars": "01_structured.ipynb",
         "proc_df": "01_structured.ipynb",
         "rf_feat_importance": "01_structured.ipynb"}

modules = ["core.py",
           "structured.py"]

doc_url = "https://lewtun.github.io/dslectures/"

git_url = "https://github.com/lewtun/dslectures/tree/master/"

def custom_doc_links(name): return None
