# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_name": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://lewtun.github.io/dslectures/"

git_url = "https://github.com/lewtun/dslectures/tree/master/"

def custom_doc_links(name): return None
